### ISSUE TITLE
s390x/ppc64le: bt2_locks.h: Error: Unrecognized opcode: `pause'

### ISSUE THREAD

**Issue by junaruga** [BenLangmead/bowtie#114]
## Summary

The following assembly error happens when building on bowtie 1.3.0 by `make` on Fedora project's Fedora 33 s390x and pcp64le build environment.

#### s390x

* GCC version: 10.2.1 (`gcc-c++-10.2.1-1.fc33.s390x`)
* `__cplusplus` macro value: `201402`

```
+ /usr/bin/make -O -j2 V=1 VERBOSE=1 allall EXTRA_FLAGS=-g
...
bt2_locks.h: Assembler messages:
bt2_locks.h:21: Error: Unrecognized opcode: `pause'
bt2_locks.h:21: Error: Unrecognized opcode: `pause'
...
```

#### ppc64le

* GCC version: 10.2.1 (`gcc-c++-10.2.1-1.fc33.ppc64le`)
* `__cplusplus` macro value: `201402`

```
+ /usr/bin/make -O -j2 V=1 VERBOSE=1 allall EXTRA_FLAGS=-g
...
/tmp/ccHpamaw.s: Assembler messages:
/tmp/ccHpamaw.s:216: Error: unrecognized opcode: `pause'
/tmp/ccHpamaw.s:227: Error: unrecognized opcode: `pause'
...
```

## Cause

The error happens at `__asm__ __volatile__("pause;");`. The code is executed on the s390x/ppc64le. But it seems the code is wrong for the CPU architectures.
On Travis s390x/ppc64le job, the code is not executed. Because the `__cplusplus` macro value is `199711`.

https://github.com/BenLangmead/bowtie/blob/1cc0a45a56197c027fdc41c4fc62752853006cc3/bt2_locks.h#L21

bt2_locks.h

```
#if (__cplusplus >= 201103L)
...
#ifdef __aarch64__
				__asm__ __volatile__("yield" ::: "memory");
#else
				__asm__ __volatile__("pause;"); /* The error happens here */
#endif
...

#endif
#endif // __MCS_LOCK_H__
```

## Possible solutions

1. Skip `#if (__cplusplus >= 201103L)` and `#endif` routine if the architecture is not x86 and not aarch64.
2. Replace the `__cplusplus >= 201103L` with `WITH_MCS_LOCK`. And control it by `make WITH_MCS_LOCK=0`.
3. Try to fix it. For example `asm volatile("or 27,27,27\n": : :"memory");` might be the code used in `__powerpc64__` instead of `pause;`. Seeing https://github.com/NVIDIA/caffe/pull/247/files . I am not familiar with it.

What do you think?

**Comment by junaruga** [comment]
I was able to reproduce this error on Travis `dist: bionic`, where `__cplusplus` macro value is `201402`, changing `.travis.yml` like this.

```
    # IBM Z (big endian)
    - os: linux
      arch: s390x
      env:
        - POPCNT_CAPABILITY=0
    - dist: bionic
      os: linux
      arch: s390x
      env:
        - POPCNT_CAPABILITY=0
    # PPC64LE
    - os: linux
      arch: ppc64le
      env:
        - POPCNT_CAPABILITY=0
    - dist: bionic
      os: linux
      arch: ppc64le
      env:
        - POPCNT_CAPABILITY=0
```
